version: "3.9"

services:
  python-dev:
    build:
      context: .
    container_name: python-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - postgres-airflow
      - postgres-analytics
    ports:
      - "8000:8000"

  postgres-airflow:
    image: postgres:13
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data

  postgres-analytics:
    image: postgres:13
    container_name: postgres-analytics
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: real_estate_analysis
    ports:
      - "5433:5432"
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data

  airflow:
    build:
      context: ./airflow/
      dockerfile: Dockerfile
    container_name: airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres-airflow
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow scheduler &
      airflow webserver --port 8080
      "

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin          
    ports:
      - "5050:80"
    volumes:
    - ./servers.json:/pgadmin4/servers.json                              
    depends_on:
      - postgres-airflow
      - postgres-analytics

volumes:
  postgres_airflow_data:
  postgres_analytics_data: